parameters:
    arduino.form.statistics.date_range:           7
    arduino.form.statistics.model_creator.class:  'KGzocha\ArduinoBundle\Service\FormHandler\Statistics\StatisticsFormModelCreator'

#   Thermometer
    arduino.form.thermometer_form.class:          'KGzocha\ArduinoBundle\Form\ThermometerForm'
    arduino.form.thermometer_form.alias:          'thermometer_form'
    arduino.form.handler.thermometer_form.class:  'KGzocha\ArduinoBundle\Service\FormHandler\Statistics\ThermometerFormHandler'


#   Pin status log
    arduino.form.pin_status_form.class:           'KGzocha\ArduinoBundle\Form\PinsForm'
    arduino.form.pin_status_form.alias:           'pins_form'
    arduino.form.handler.pin_status_form.class:   'KGzocha\ArduinoBundle\Service\FormHandler\Statistics\PinsFormHandler'

#   Response log
    arduino.form.response_form.class:             'KGzocha\ArduinoBundle\Form\ResponseTimeForm'
    arduino.form.response_form.alias:             'response_time_form'
    arduino.form.handler.response_form.class:     'KGzocha\ArduinoBundle\Service\FormHandler\Statistics\ResponseTimeFormHandler'

#   Conenctor settings form
    arduino.settings_saver.class:                   'KGzocha\ArduinoBundle\Service\FormHandler\SettingsForm\SettingsSaver'
    arduino.form.handler.settings.connector.prefix: 'connector.'
    arduino.form.settings.connector_class.class:    'KGzocha\ArduinoBundle\Form\SettingsForm\Connector\ConnectorClassSettings'
    arduino.form.settings.connector_class.alias:    'connector_class_settings'
    arduino.form.handler.settings.connector.class:  'KGzocha\ArduinoBundle\Service\FormHandler\SettingsForm\Connector\ConnectorSettingsFormHandler'
    arduino.form.settings.connector_classes:
        - 'KGzocha\ArduinoBundle\Service\ArduinoConnector\WebConnector'

    arduino.form.settings.connector.web_connector.methods:
        - 'GET'
        - 'POST'

    arduino.form.settings.connector.web_connector.protocols:
        - 'http'
        - 'https'

    arduino.form.settings.connector.web_connector.class:  'KGzocha\ArduinoBundle\Service\ArduinoConnector\Settings\SettingsForms\WebConnectorForm'
    arduino.form.settings.connector.web_connector.alias:  'connector_settings_web_connector'

services:
    arduino.form.statistics.model_creator:
        class:  %arduino.form.statistics.model_creator.class%
        lazy:   true
        arguments: [@doctrine.orm.entity_manager, %arduino.form.statistics.date_range%]

    arduino.form.thermometer_form:
        class:  %arduino.form.thermometer_form.class%
        lazy:   true
        arguments: [%arduino.form.thermometer_form.alias%]
        tags:
            - { name: form.type, alias: %arduino.form.thermometer_form.alias% }

    arduino.form.handler.thermometer_form:
        class:  %arduino.form.handler.thermometer_form.class%
        lazy:   true
        arguments: [@form.factory, @arduino.form.statistics.model_creator, %arduino.form.thermometer_form.alias%]

    arduino.form.pin_status_form:
        class:  %arduino.form.pin_status_form.class%
        lazy:   true
        arguments: [%arduino.form.pin_status_form.alias%]
        tags:
            - { name: form.type, alias: %arduino.form.pin_status_form.alias% }

    arduino.form.handler.pin_status_form:
        class:  %arduino.form.handler.pin_status_form.class%
        lazy:   true
        arguments: [@form.factory, @arduino.form.statistics.model_creator, %arduino.form.pin_status_form.alias%]

    arduino.form.response_form:
        class:  %arduino.form.response_form.class%
        lazy:   true
        arguments: [%arduino.form.response_form.alias%]
        tags:
            - { name: form.type, alias: %arduino.form.response_form.alias% }

    arduino.form.handler.response_form:
        class:  %arduino.form.handler.response_form.class%
        lazy:   true
        arguments:  [@form.factory, @arduino.form.statistics.model_creator, %arduino.form.response_form.alias%]

#   Settings form

    arduino.settings_saver:
        class:  %arduino.settings_saver.class%
        lazy:   true
        arguments: [@doctrine.orm.entity_manager]

    arduino.form.settings.connector_class:
        class:  %arduino.form.settings.connector_class.class%
        lazy:   true
        tags:
            - { name: form.type, alias: %arduino.form.settings.connector_class.alias% }
        calls:
            - [setChoiceList, [%arduino.form.settings.connector_classes%]]

    arduino.form.settings.connector.web_connector:
        class:  %arduino.form.settings.connector.web_connector.class%
        lazy:   true
        tags:
            - { name: form.type, alias: %arduino.form.settings.connector.web_connector.alias% }
        calls:
            - [setMethods, [%arduino.form.settings.connector.web_connector.methods%]]
            - [setProtocols, [%arduino.form.settings.connector.web_connector.protocols%]]

    arduino.form.handler.settings.connector:
        class:  %arduino.form.handler.settings.connector.class%
        lazy:   true
        arguments: [@form.factory, @arduino.settings_saver, @doctrine.orm.entity_manager, %arduino.form.handler.settings.connector.prefix%]
        calls:
            - [addConenctorSettingsClass, [@arduino.connector.settings.web_from_db]]
