parameters:
    arduino.response.response_handler.class:          'KGzocha\ArduinoBundle\Service\ResponseHandler\ResponseHandler'
#    StripTagsProcessor
    arduino.response.processor.strip_tags.class:      'KGzocha\ArduinoBundle\Service\ResponseHandler\Processor\StripTagsProcessor'
#    LogTemperatureProcessor
    arduino.response.processor.log_temp.class:        'KGzocha\ArduinoBundle\Service\ResponseHandler\Processor\LogTemperatureProcessor'
    arduino.response.processor.log_temp.temp_format:  '/T([1-9]{1,3}): ([+-]{0,1}[\.0-9]{1,6})/i'
    arduino.response.processor.log_temp.therm_place:  1
    arduino.response.processor.log_temp.value_place:  2
    arduino.response.processor.log_temp.new_thermometer:  'Unidentified thermometer %d.'
#    LogPinStatusProcessor
    arduino.response.processor.log_pin_status.class:        'KGzocha\ArduinoBundle\Service\ResponseHandler\Processor\LogPinStatusProcessor'
    arduino.response.processor.log_pin_status.format:       '/P([aA]*[0-9]{1,2}): ([0-9]{1,4})/i'
    arduino.response.processor.log_pin_status.pin_place:    1
    arduino.response.processor.log_pin_status.value_place:  2

services:
    arduino.response.processor.strip_tags:
        class:      %arduino.response.processor.strip_tags.class%
        lazy:       true

    arduino.response.processor.log_temp:
        class:      %arduino.response.processor.log_temp.class%
        arguments:  [@doctrine.orm.entity_manager, %arduino.response.processor.log_temp.temp_format%]
        lazy:       true
        calls:
            - [setThermometerPlaceInFormat, [%arduino.response.processor.log_temp.therm_place%]]
            - [setTempValuePlaceInFormat, [%arduino.response.processor.log_temp.value_place%]]
            - [setUnidentifiedThermometerName, [%arduino.response.processor.log_temp.new_thermometer%]]

    arduino.response.processor.log_pin_status:
        class:      %arduino.response.processor.log_pin_status.class%
        arguments:  [@doctrine.orm.entity_manager, %arduino.response.processor.log_pin_status.format%]
        lazy:       true
        calls:
            - [setPinNumberPlace, [%arduino.response.processor.log_pin_status.pin_place%]]
            - [setPinValuePlace, [%arduino.response.processor.log_pin_status.value_place%]]

    arduino.response.response_handler:
        class:      %arduino.response.response_handler.class%
        arguments:  [@doctrine.orm.entity_manager]
        lazy:       true
        calls:
            - [addProcessor, [@arduino.response.processor.strip_tags]]
            - [addProcessor, [@arduino.response.processor.log_temp]]
            - [addProcessor, [@arduino.response.processor.log_pin_status]]
