arduino_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ArduinoBundle:Default:index }

arduino_statistics:
    resource: "@ArduinoBundle/Controller/StatisticsController.php"

arduino_settings:
    resource: "@ArduinoBundle/Controller/SettingsController.php"

arduino_settings:
    resource: "@ArduinoBundle/Controller/ThermometerController.php"
