parameters:
    arduino.connector.settings_prefix:  "connector."
    arduino.connector.factory.class:    "KGzocha\ArduinoBundle\Service\ArduinoConnector\ConnectorFactory"

services:
    arduino.connector.factory:
        class:      %arduino.connector.factory.class%
        arguments:  [@doctrine.orm.entity_manager, %arduino.connector.settings_prefix%]
        lazy:       true

#    arduino.example:
#        class: %arduino.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
