parameters:
    arduino.connector.settings_prefix:            'connector.'
    arduino.connector.factory.class:              'KGzocha\ArduinoBundle\Service\ArduinoConnector\ConnectorFactory'
    arduino.connector.settings.web_from_db.class: 'KGzocha\ArduinoBundle\Service\ArduinoConnector\Settings\WebConnectorSettingsFromDatabase'
    arduino.response.response_handler.class:      'KGzocha\ArduinoBundle\Service\ResponseHandler\ResponseHandler'
    arduino.response.processor.strip_tags.class:  'KGzocha\ArduinoBundle\Service\ResponseHandler\Processor\StripTagsProcessor'

services:
    arduino.connector.factory:
        class:      %arduino.connector.factory.class%
        arguments:  [@arduino.connector.settings.web_from_db, @arduino.response.response_handler]
        lazy:       true

    arduino.connector.settings.web_from_db:
        class:      %arduino.connector.settings.web_from_db.class%
        arguments:  [@doctrine.orm.entity_manager, %arduino.connector.settings_prefix%]
        lazy:       true

    arduino.response.processor.strip_tags:
        class:      %arduino.response.processor.strip_tags.class%

    arduino.response.response_handler:
        class:      %arduino.response.response_handler.class%
        arguments:  [@doctrine.orm.entity_manager]
        lazy:       true
        calls:
            - [addProcessor, ['@arduino.response.processor.strip_tags']]
