<?php

namespace KGzocha\ArduinoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingsRepository extends EntityRepository
{

	/**
	 * @param $prefix
	 *
	 * @return arrays
	 */
	public function findAllByPrefix($prefix)
	{
		return $this
			->createQueryBuilder('s')
			->where('s.name LIKE :prefix')
			->setParameter('prefix', sprintf('%s%%', $prefix))
			->orderBy('s.name', 'ASC')
			->getQuery()
			->useResultCache(true, 3600)
			->getResult();
	}

}
