<?php

namespace KGzocha\ArduinoBundle\Repository;

use Doctrine\ORM\EntityRepository;
use KGzocha\ArduinoBundle\Entity\Thermometer;

/**
 * ThermometerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThermometerRepository extends EntityRepository
{
    /**
     * @return Thermometer|null
     */
    public function findFirstThermometer()
    {
        return $this->createQueryBuilder('t')
            ->orderBy('t.id', 'asc')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
